/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <hamsandwich>
#include <fun>
#include <cstrike>
#include <engine>
native jb_get_user_packs(id)
native jb_set_user_packs(id, ammount)

#define PLUGIN "Batman"
#define VERSION "0.1"
#define AUTHOR "burakware"

new batman_ucma[64],dusme_hasari[33];

public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	RegisterHam(Ham_TakeDamage, "player", "OnCBasePlayer_TakeDamage")
	register_clcmd("say /batman","batmanol")
	register_logevent("Event_RoundStart", 2, "1=Round_Start")
}

public Event_RoundStart()
{
	for(new i; i < get_maxplayers(); i++) {
		dusme_hasari[i] = false
		batman_ucma[i] = false
	}
}

public batmanol(id) { 
	if(get_user_team(id) == 1) {
		if(jb_get_user_packs(id) >= 120) {
			new isimcik[64]
			get_user_name(id,isimcik,63)
			set_user_health(id,200)
			set_user_armor(id,150)
			set_user_maxspeed(id,280.0)
			dusme_hasari[id] = true
			batman_ucma[id] = true
			jb_set_user_packs(id,jb_get_user_packs(id) - 120)
			client_printc(0,"!n[ !tShieldsClan !n] !t[ !g%s !t] !nIsimli Oyuncu !gBatman'a !nDonustu!",isimcik)
			client_printc(id,"!n[ !tShieldsClan !n] !gBatman'a !ndonustun. !t200HP !n, !t150 Armor !n, !tYuksekten Can Gitmeme !nOzellikleri Aldin!")
			client_printc(id,"!n[ !tShieldsClan !n] !n[!tBosluk!n] !g Tusuna Basarak Ucabilirsin.")
		}
		else {
			client_printc(id,"!n[ !tShieldsClan !n] !gYeterli Paran Yok!")
		}
	}

}
public client_PreThink(id){
		if(batman_ucma[id] == 1){
			if(!(get_user_button(id) & IN_JUMP)) {
			return PLUGIN_CONTINUE;
			}
			new Float:fAim[3] , Float:fVelocity[3];
			VelocityByAim(id , 700 , fAim);
			
			fVelocity[0] = fAim[0];
			fVelocity[1] = fAim[1];
			fVelocity[2] = fAim[2];
			
			set_user_velocity(id , fVelocity);
			}
		return PLUGIN_CONTINUE
}
public OnCBasePlayer_TakeDamage( id, iInflictor, iAttacker, Float:flDamage, bitsDamageType )
{
	if( bitsDamageType & DMG_FALL && dusme_hasari[id])
	{
		return HAM_SUPERCEDE
	}
	return PLUGIN_CONTINUE
}
stock client_printc(const id, const input[], any:...)
{
	new count = 1, players[32];
	static msg[191];
	vformat(msg, 190, input, 3);
	
	replace_all(msg, 190, "!n", "^x01"); // Default Renk(Sar�)
	replace_all(msg, 190, "!g", "^x04"); // Ye�il Renk
	replace_all(msg, 190, "!t", "^x03"); // Tak�m Renk( CT mavi , T k�rm�z� )
	
	if (id) players[0] = id; else get_players(players, count, "ch");
	{
		for (new i = 0; i < count; i++)
		{
			if (is_user_connected(players[i]))
			{
				
				message_begin(MSG_ONE_UNRELIABLE, get_user_msgid("SayText"), _, players[i]);
				write_byte(players[i]);
				write_string(msg);
				message_end();
			}

		}
	}
}
